//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttend
    {
        public int Emp_Id { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public bool Attended { get; set; }
        public Nullable<System.TimeSpan> Attendance { get; set; }
        public Nullable<System.TimeSpan> Leave { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
